config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#index'
  resources :messages
  resources :conversations

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  has_many :users
  has_many :messages
  


  def label(user_id)
    # if the user_id matches sender_user_id
    # return the receiver else return the sender
    if user_id == sender_user_id
      return receiver.email
    else
      return sender.email
    end
  end

  def receiver
    User.find(receiver_user_id)
  end

  def sender
    User.find(sender_user_id)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User", foreign_key: "sender_user_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_user_id"
  belongs_to :conversation

  validates :receiver_user_id, presence: true
  validates :sender_user_id, presence: true


  #put method for messages conversation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :received_messages, class_name: "Message", foreign_key: "receiver_user_id"
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_user_id"
  has_many :conversations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = Conversation.order("created_at desc").all
  end

  def show
    @conversation = Conversation.find(params[:id])
  end

  def new
    @conversation = Conversation.new
  end

private



end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  def index
    # only see messages I sent or messages to messages
    @messages = Message.where("receiver_user_id = ? OR sender_user_id = ?",
      current_user.id, current_user.id).order("created_at desc")

  end

  def new
    @message = Message.new
  end

  def create
    # if have conversation id in params, use this to set conversation id on new message
    # else make new conversation
    if message_params[:conversation_id].present?
      @message = Message.new(message_params)
    else
      @conversation = Conversation.create!(sender_user_id: message_params[:sender_user_id],
        receiver_user_id: message_params[:receiver_user_id])
      @message = Message.new(message_params)
      @message.conversation_id=@conversation.id
    end

    if @message.save
      respond_to do |format|
        format.html {redirect_to conversation_path(@conversation)}
        format.json {
          json_content = render_to_string partial: "messages/display.html.erb", locals: {message: @message}, layout: false
          render json: {
            content: json_content,
            status: :ok
          }
        }
      end
    else
      render :new
    end

  end

  def show
    @messages = Message.all
  end

  private

  def message_params
    params.require(:message).permit(:sender_user_id, :receiver_user_id, :body, :conversation_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/conversations/index.html.erb
<h1>Conversation Page</h1>

<%= link_to "New Conversation", new_message_path %>
<br/> <br/>
<div class="booyah-box col-sm-8 col-sm-offset-2">
  <% @conversations.each do |conversation| %>
     <div class= "row">
      <%= link_to conversation.label(current_user.id), conversation %>
    </div>
   <br/>
  <% end %>
 </div>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>


app/views/conversations/show.html.erb
<%= render partial: "messages/form", locals:{conversation: @conversation} %>

<%= render partial: "messages/list", locals:{messages: @conversation.messages.order("created_at desc")} %>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mmchat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" </a>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
        <li><%= link_to 'Conversations', conversations_path %></li>
        
      </ul>

      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
          <li><%= link_to "Sign Out #{current_user.email}", destroy_user_session_path, method: :delete %></li>

          <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/messages/_display.html.erb
<li>
  <% if message.sender_user_id == current_user.id %>
    <div class="row">
      <div class="col-xs-4 col-xs-offset-8">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="panel-title">
              To: <%= message.receiver.email %>
            <br>
             <%= local_time(message.created_at.strftime("%b %d, %Y at %I:%M %p")) %>
            <br>
              <div class="panel-body text-right">
                <%= message.body %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-xs-4 panel">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              From: <%= message.sender.email %>
            <br>
              <%= local_time(message.created_at.strftime("%b %d, %Y at %I:%M %p")) %>
            <br>
              <div class="panel-body text-right">
                <%= message.body %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</li>

app/views/messages/_form.html.erb

<form class="form-horizontal">
  <%= hidden_field_tag :sender_user_id, current_user.id %>

  <% if conversation %>
    <%= hidden_field_tag :conversation_id, conversation.id %>
    <%= hidden_field_tag :message_receiver_receiver_id, conversation.receiver_user_id %>
  <% else %>
    <div class="form-group ">
      <div class="col-sm-8 col-sm-offset-2">
        <%= collection_select(:message_receiver, :receiver_id, User.where("id <> ?",current_user.id), :id, :email, prompt: true) %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <label for="messsage" class="col-sm-2 control-label">Message</label>
    <div class="col-sm-8">
      <input type="text" class="form-control" id="messsage-body" placeholder="">
    </div>
    <div class="col-sm-2">
      <a id="send-message" href="javascript:void(0)" class="btn btn-success">Send</a>
    </div>
  </div>
</form>

app/views/messages/_list.html.erb
<ul id="js-message-list" style="list-style-type: none;">
  <% messages.each do |message| %>
      <%= render partial: "messages/display", locals:{message: message} %>
  <% end %>
</ul>

app/views/messages/index.html.erb
<%= render partial: "form", locals:{conversation: nil} %>

<%= render partial: "list", locals:{messages: @messages} %>

app/views/messages/new.html.erb

  <h1>Enter Your Message</h1>
  <br />


    
    <%= simple_form_for @message do |f| %>
      <%= f.hidden_field :sender_user_id, value: current_user.id %>
  
      <%= f.association :receiver, collection: User.where("id <> ?",current_user.id), label_method: :email %>
      <br />
      <%= f.input :body, as: :text, label: "Message" %>
      <br />
      <%= f.button :submit, class: 'btn btn-success' %>
    <% end %>


  



app/views/messages/show.html.erb

<% @messages.each do |message| %>
   <%= message.body %>
   
  
  <% end %>


app/views/pages/index.html.erb
<%= link_to "Messages", messages_path %>

<%= link_to "Conversations", conversations_path %>